In [ ]:
# ============================================================
# TASK 2 - DATA CLEANING USING PANDAS
# GLOBAL SUPERSTORE DATASET
# ============================================================

import pandas as pd
from google.colab import files

# ------------------------------------------------------------
# 1. UPLOAD DATASET
# ------------------------------------------------------------

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

# Load CSV
df = pd.read_csv(file_name)

print("==============================================")
print("DATASET LOADED SUCCESSFULLY")
print("==============================================")

print("File Name:", file_name)
print("Original Rows:", len(df))
print("Original Columns:", len(df.columns))

# ------------------------------------------------------------
# 2. DISPLAY ORIGINAL DATA
# ------------------------------------------------------------

print("\n========== ORIGINAL DATA ==========")

display(df.head(10))

# ------------------------------------------------------------
# 3. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n========== MISSING VALUES ==========")

missing = df.isnull().sum()

print(missing)

print(
    "\nTotal Missing Values:",
    df.isnull().sum().sum()
)

# ------------------------------------------------------------
# 4. CHECK DUPLICATES
# ------------------------------------------------------------

print("\n========== DUPLICATE ROWS ==========")

duplicate_count = df.duplicated().sum()

print(
    "Duplicate Rows Found:",
    duplicate_count
)

# Remove duplicates
df = df.drop_duplicates()

print(
    "Rows After Removing Duplicates:",
    len(df)
)

# ------------------------------------------------------------
# 5. CONVERT DATE COLUMNS
# ------------------------------------------------------------

print("\n========== DATA TYPE CONVERSION ==========")

# Order Date
if "Order Date" in df.columns:

    df["Order Date"] = pd.to_datetime(
        df["Order Date"],
        errors="coerce"
    )

    print(
        "Order Date:",
        df["Order Date"].dtype
    )

# Ship Date
if "Ship Date" in df.columns:

    df["Ship Date"] = pd.to_datetime(
        df["Ship Date"],
        errors="coerce"
    )

    print(
        "Ship Date:",
        df["Ship Date"].dtype
    )

# ------------------------------------------------------------
# 6. CONVERT NUMERIC COLUMNS
# ------------------------------------------------------------

numeric_columns = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit",
    "Postal Code"
]

for column in numeric_columns:

    if column in df.columns:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

        print(
            column,
            "->",
            df[column].dtype
        )

# ------------------------------------------------------------
# 7. HANDLE MISSING VALUES
# ------------------------------------------------------------

print("\n========== HANDLING MISSING VALUES ==========")

# Numeric columns
numeric_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns

for column in numeric_cols:

    if df[column].isnull().sum() > 0:

        df[column] = df[column].fillna(
            df[column].median()
        )

# Text columns
text_cols = df.select_dtypes(
    include=["object"]
).columns

for column in text_cols:

    if df[column].isnull().sum() > 0:

        df[column] = df[column].fillna(
            "Unknown"
        )

# ------------------------------------------------------------
# 8. CHECK MISSING VALUES AFTER CLEANING
# ------------------------------------------------------------

print("\n========== AFTER CLEANING ==========")

print(
    "Total Missing Values:",
    df.isnull().sum().sum()
)

print(
    "Total Duplicate Rows:",
    df.duplicated().sum()
)

# ------------------------------------------------------------
# 9. FINAL DATA TYPES
# ------------------------------------------------------------

print("\n========== FINAL DATA TYPES ==========")

print(df.dtypes)

# ------------------------------------------------------------
# 10. FINAL CLEANED DATA
# ------------------------------------------------------------

print("\n========== CLEANED DATA ==========")

display(df.head(20))

# ------------------------------------------------------------
# 11. EXPORT CLEANED DATA
# ------------------------------------------------------------

output_file = "Cleaned_Global_Superstore.csv"

df.to_csv(
    output_file,
    index=False
)

print("\n==============================================")
print("DATA CLEANING COMPLETED SUCCESSFULLY!")
print("==============================================")

print("Final Rows:", len(df))
print("Final Columns:", len(df.columns))

print(
    "Cleaned File:",
    output_file
)

# ------------------------------------------------------------
# 12. DOWNLOAD CSV
# ------------------------------------------------------------

files.download(output_file)

Saving train.csv to train (1).csv
==============================================
DATASET LOADED SUCCESSFULLY
==============================================
File Name: train (1).csv
Original Rows: 9800
Original Columns: 18

========== ORIGINAL DATA ==========

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
8,9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040
9,10,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000

========== MISSING VALUES ==========
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

Total Missing Values: 11

========== DUPLICATE ROWS ==========
Duplicate Rows Found: 0
Rows After Removing Duplicates: 9800

========== DATA TYPE CONVERSION ==========
Order Date: datetime64[ns]
Ship Date: datetime64[ns]
Sales -> float64
Postal Code -> float64

========== HANDLING MISSING VALUES ==========

========== AFTER CLEANING ==========
Total Missing Values: 11826
Total Duplicate Rows: 0

========== FINAL DATA TYPES ==========
Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
dtype: object

========== CLEANED DATA ==========

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,2017-12-06,NaT,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,2016-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,2016-11-10,NaT,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
5,6,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
6,7,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800
7,8,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
8,9,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040
9,10,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000
10,11,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840
11,12,CA-2015-115812,2015-09-06,NaT,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240
12,13,CA-2018-114412,NaT,NaT,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520
13,14,CA-2017-161389,2017-05-12,2017-10-12,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,98103.0,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760
14,15,US-2016-118983,NaT,NaT,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100
15,16,US-2016-118983,NaT,NaT,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440
16,17,CA-2015-105893,2015-11-11,NaT,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711.0,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800
17,18,CA-2015-167164,NaT,NaT,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,Utah,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.5000
18,19,CA-2015-143336,NaT,2015-01-09,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.5600
19,20,CA-2015-143336,NaT,2015-01-09,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.4800

==============================================
DATA CLEANING COMPLETED SUCCESSFULLY!
==============================================
Final Rows: 9800
Final Columns: 18
Cleaned File: Cleaned_Global_Superstore.csv